sudo: required
language: bash
env:
  global:
  - IMAGE_NAME=gableroux/unity3d:2018.2.6f1
  - BUILD_NAME=ExampleProjectName
  - UNITY_VERSION=2018.2.6f1
services:
- docker
before_install:
- docker pull $IMAGE_NAME
script: >
  docker run -it --rm 
  -e "UNITY_USERNAME=ci@litefeel.com" 
  -e "UNITY_PASSWORD=123456Qq" 
  -e "TEST_PLATFORM=linux" 
  -e "WORKDIR=/root/project" 
  -v "$(pwd):/root/project" 
  gableroux/unity3d:$UNITY_VERSION 
  bash
